var naturesGer = {
    "1": "Robust",
    "2": "K\u00fchn",
    "3": "M\u00e4\u00dfig",
    "4": "Still",
    "5": "Scheu",
    "6": "Solo",
    "7": "Sanft",
    "8": "Mild",
    "9": "Zart",
    "10": "Hastig",
    "11": "Hart",
    "12": "Pfiffig",
    "13": "Zaghaft",
    "14": "Sacht",
    "15": "Hitzig",
    "16": "Froh",
    "17": "Frech",
    "18": "Lasch",
    "19": "Kauzig",
    "20": "Naiv",
    "21": "Mutig",
    "22": "Locker",
    "23": "Ruhig",
    "24": "Forsch",
    "25": "Ernst"
}
