var naturesIta = {
    "1": "Ardita",
    "2": "Sicura",
    "3": "Modesta",
    "4": "Calma",
    "5": "Timida",
    "6": "Schiva",
    "7": "Docile",
    "8": "Mite",
    "9": "Gentile",
    "10": "Lesta",
    "11": "Decisa",
    "12": "Scaltra",
    "13": "Ritrosa",
    "14": "Cauta",
    "15": "Ardente",
    "16": "Allegra",
    "17": "Birbona",
    "18": "Fiacca",
    "19": "Furba",
    "20": "Ingenua",
    "21": "Audace",
    "22": "Placida",
    "23": "Quieta",
    "24": "Vivace",
    "25": "Seria"
}
