var NatureTranslator = {
    "Hardy": "1",
    "Bold": "2",
    "Modest": "3",
    "Calm": "4",
    "Timid": "5",
    "Lonely": "6",
    "Docile": "7",
    "Mild": "8",
    "Gentle": "9",
    "Hasty": "10",
    "Adamant": "11",
    "Impish": "12",
    "Bashful": "13",
    "Careful": "14",
    "Rash": "15",
    "Jolly": "16",
    "Naughty": "17",
    "Lax": "18",
    "Quirky": "19",
    "Naive": "20",
    "Brave": "21",
    "Relaxed": "22",
    "Quiet": "23",
    "Sassy": "24",
    "Serious": "25"
}
